# Generated by Django 3.1.3 on 2021-01-27 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('stripe_checkout_id', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('payment_status', models.CharField(max_length=50)),
                ('purchase_type', models.CharField(max_length=50)),
                ('purchase_choice', models.CharField(max_length=50)),
                ('ad_uuid', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
