# Generated by Django 3.0.2 on 2020-09-02 08:05

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default=None, help_text='Upload an image for your avatar.', null=True, storage=app.storage_backends.S3UserAccountStorage(), upload_to=''),
        ),
    ]
