# Generated by Django 3.0.2 on 2020-02-14 07:20

import app.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='What is the name of this event?', max_length=150)),
                ('slug', models.SlugField(default='')),
                ('host', models.CharField(blank=True, default='', help_text='What organisation is hosting this event?', max_length=250, null=True)),
                ('image', models.ImageField(blank=True, default=None, help_text='Upload an image or poster for this event.', null=True, storage=app.storage_backends.S3EventsMediaStorage(), upload_to='')),
                ('attachment', models.FileField(blank=True, default=None, help_text='Upload a PDF file.', null=True, storage=app.storage_backends.S3EventsFileStorage(), upload_to='')),
                ('link', models.URLField(blank=True, default=None, help_text='Add a link to your website or the event webpage here.', null=True)),
                ('location', models.CharField(default=None, help_text='Where will this event take place?', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Here is where you can talk about your event in greater detail.', null=True)),
                ('email_contact', models.EmailField(blank=True, default=None, help_text='Where can people email with any questions?', max_length=254, null=True)),
                ('phone_contact', models.CharField(blank=True, default=None, help_text='Where can people call with any questions?', max_length=18, null=True)),
                ('video', models.URLField(blank=True, default=None, help_text='Include a video about your event.', max_length=300, null=True)),
                ('start_time', models.TimeField(blank=True, default=None, help_text='What time does your event start?', null=True)),
                ('start_date', models.DateField(default=None, help_text='When will your event take place?')),
                ('end_date', models.DateField(blank=True, default=None, help_text='If your event occurs over multiple days, when will your event end?', null=True)),
                ('rsvp', models.BooleanField(default=None, help_text='Does your event require RSVP or tickets?', verbose_name='RSVP')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='If anything, how much will it cost to attend your event?', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
