# Generated by Django 3.0.2 on 2020-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='suburb',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='numbers only, currency symbol will not work.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, default=None, help_text='A link to your website or event webpage.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=None, help_text='HOUR:MINUTE:AM/PM', null=True, verbose_name='Start Time'),
        ),
    ]
