# Generated by Django 3.0.2 on 2020-01-28 07:25

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.FileField(default='', storage=app.storage_backends.AzureMediaStorage(), upload_to=''),
        ),
    ]
