# Generated by Django 3.0.2 on 2020-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200225_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
