# Generated by Django 3.0.2 on 2020-01-28 07:39

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.FileField(default='', storage=app.storage_backends.EventMediaStorage(), upload_to=''),
        ),
    ]
