# Generated by Django 3.0.2 on 2020-02-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.TextField(blank=True, default=None, help_text='Add a link to a youtube video. Must be a URL not an embed.', max_length=300, null=True),
        ),
    ]
