# Generated by Django 3.0.2 on 2020-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200129_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
