# Generated by Django 3.0.2 on 2020-06-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200225_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.CharField(blank=True, default=None, help_text='Add a link to a youtube/vimeo video.', max_length=300, null=True),
        ),
    ]
