# Generated by Django 3.0.2 on 2020-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200130_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
