# Generated by Django 3.0.2 on 2020-06-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200621_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='suburb',
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Numbers only, currency symbol will not work.', max_digits=8, null=True),
        ),
    ]
