# Generated by Django 3.0.2 on 2020-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200629_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'events category',
                'verbose_name_plural': 'events categories',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='events.EventsCategory'),
        ),
    ]
