# Generated by Django 3.0.2 on 2020-01-30 14:27

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200130_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_attachment',
            field=models.FileField(blank=True, default=None, help_text='Upload a PDF file.', null=True, storage=app.storage_backends.EventFileStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, help_text='Here is where you can talk about your event in greater detail.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_email_contact',
            field=models.EmailField(blank=True, default=None, help_text='Where can people email with any questions?', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.CharField(blank=True, default='', help_text='What organisation is hosting this event?', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.FileField(blank=True, default=None, help_text='Upload an image or poster for this event.', null=True, storage=app.storage_backends.EventMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.URLField(blank=True, default=None, help_text='Add a link to your website or the event webpage here.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_phone_contact',
            field=models.CharField(blank=True, default=None, help_text='Where can people call with any questions?', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_video',
            field=models.URLField(blank=True, default=None, help_text='Include a video about your event.', max_length=300, null=True),
        ),
    ]
