# Generated by Django 3.0.2 on 2020-01-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200130_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_attachment',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_email_contact',
            new_name='email_contact',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_host',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_phone_contact',
            new_name='phone_contact',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_rsvp',
            new_name='rsvp',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_video',
            new_name='video',
        ),
    ]
