# Generated by Django 3.0.2 on 2020-02-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200130_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='If anything, how much will it cost to attend your event?', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='If your event occirs of multiple days, when will your event end?', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=None, help_text='When will your event take place?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=None, help_text='What time does your event start?', null=True),
        ),
    ]
