# Generated by Django 3.0.2 on 2020-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200202_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='If your event occurs over multiple days, when will your event end?', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp',
            field=models.BooleanField(default=None, help_text='Does your event require RSVP or tickets?', verbose_name='RSVP'),
        ),
    ]
