# Generated by Django 3.1.3 on 2020-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default=None, help_text='Address where this event take place...', max_length=500, null=True),
        ),
    ]
