# Generated by Django 3.0.2 on 2020-02-04 17:47

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200204_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Upload an image or poster for this event.', null=True, storage=app.storage_backends.EventMediaStorage(), upload_to=''),
        ),
    ]
