# Generated by Django 3.1.3 on 2020-12-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201201_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_virtual_event',
            field=models.BooleanField(default=False, help_text='Check this box if this is an online only event.', verbose_name='Virtual Event'),
        ),
    ]
