# Generated by Django 3.0.2 on 2020-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200719_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivers',
            field=models.BooleanField(default=False),
        ),
    ]
