# Generated by Django 3.0.2 on 2020-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200810_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(to='listings.Category'),
        ),
    ]
