# Generated by Django 3.0.2 on 2020-08-31 14:29

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200810_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cover_image',
            field=models.ImageField(blank=True, default=None, help_text='Upload a cover image for your listing.', null=True, storage=app.storage_backends.S3ListingsMediaStorage(), upload_to=''),
        ),
    ]
