# Generated by Django 3.0.2 on 2020-09-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listingtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingType',
            new_name='CategoryGroup',
        ),
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'verbose_name': 'category group', 'verbose_name_plural': 'category groups'},
        ),
    ]
