# Generated by Django 3.0.2 on 2020-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200903_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category_groups',
            field=models.ManyToManyField(to='listings.CategoryGroup'),
        ),
    ]
