# Generated by Django 3.0.2 on 2020-09-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_listing_category_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_groups',
            field=models.ManyToManyField(blank=True, to='listings.CategoryGroup'),
        ),
    ]
