# Generated by Django 3.0.2 on 2020-09-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_auto_20200903_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category_groups',
        ),
    ]
