# Generated by Django 3.0.2 on 2020-10-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_remove_listing_category_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='fax',
        ),
    ]
