# Generated by Django 3.0.2 on 2020-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_listing_fax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'verbose_name': 'Category Group', 'verbose_name_plural': 'Category Groups'},
        ),
        migrations.AlterField(
            model_name='listing',
            name='facebook',
            field=models.URLField(blank=True, default='', help_text='Enter the URL of your Facebook page if you have one. (Must include http:// or https://)', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='instagram',
            field=models.URLField(blank=True, default='', help_text='Enter the URL of your Instagram page if you have one. (Must include http:// or https://)', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='kashrut',
            field=models.CharField(blank=True, default=None, help_text='What Kashrut do you have.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='twitter',
            field=models.URLField(blank=True, default='', help_text='Enter the URL of your Twitter page if you have one. (Must include http:// or https://)', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Enter the URL of your website if you have one. (Must include http:// or https://)', null=True),
        ),
    ]
