# Generated by Django 3.1.3 on 2020-12-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_auto_20201115_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Save for Later'), ('published', 'Published')], default='draft', help_text='Listings will not show until Published', max_length=50),
        ),
    ]
