# Generated by Django 3.1.3 on 2020-12-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_auto_20201206_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
