# Generated by Django 3.1.8 on 2021-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_auto_20201230_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
