# Generated by Django 3.1.12 on 2021-08-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_auto_20210825_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listinglike',
            options={'verbose_name': 'like', 'verbose_name_plural': 'likes'},
        ),
    ]
