# Generated by Django 3.0.2 on 2020-01-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=50, verbose_name='name of the page')),
                ('meta_title', models.CharField(max_length=70, verbose_name='page title for search engines/tab name/bookmarking')),
                ('meta_description', models.CharField(max_length=150, verbose_name='page description for search engines')),
            ],
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=50, verbose_name='descriptive name for this content')),
                ('content', models.TextField(verbose_name='value for the content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='to which page does this belong')),
            ],
        ),
    ]
