# Generated by Django 3.0.2 on 2020-01-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'verbose_name': 'Page Content', 'verbose_name_plural': 'Page Contents'},
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(max_length=150, verbose_name='page description for search engines'),
        ),
    ]
