# Generated by Django 3.0.2 on 2020-02-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200122_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.ForeignKey(help_text='To which page does this belong', on_delete=django.db.models.deletion.CASCADE, related_name='page', to='pages.Page', verbose_name='page name'),
        ),
    ]
