# Generated by Django 3.0.2 on 2020-07-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200214_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
    ]
