# Generated by Django 3.0.2 on 2020-11-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0006_auto_20200719_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('phone', models.CharField(blank=True, default=None, max_length=18, null=True)),
                ('subject', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Support', 'Support'), ('Feature Request', 'Feature Request'), ('Advertising', 'Advertising')], default='General Inquiry', max_length=50)),
                ('message', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
