# Generated by Django 3.1.3 on 2020-11-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201102_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(default=None, max_length=255)),
                ('post_id', models.IntegerField(default=None)),
                ('post_title', models.CharField(default=None, max_length=255)),
                ('report_reason', models.CharField(choices=[('Content', 'Inappropriate Content'), ('Images', 'Inappropriate Images'), ('Quality', 'Rude, Vulgar, or Offensive'), ('Ownership', 'Copyright / Trademark Issue'), ('Spam', 'Spam Content')], max_length=50)),
                ('message', models.TextField(blank=True, default=None)),
                ('user_id', models.IntegerField(blank=True, default=None)),
                ('name', models.CharField(blank=True, default=None, max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=255)),
            ],
            options={
                'verbose_name': 'Report Post',
                'verbose_name_plural': 'Report Posts',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Feature Request', 'Feature Request'), ('General Inquiry', 'General Inquiry'), ('Suggestion', 'Suggestion'), ('Support', 'Support')], default='General Inquiry', max_length=50),
        ),
    ]
