# Generated by Django 3.1.3 on 2020-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20201104_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AlterModelOptions(
            name='reportpost',
            options={'verbose_name': 'Reported Post', 'verbose_name_plural': 'Reported Posts'},
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
