# Generated by Django 3.1.3 on 2020-11-12 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201104_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
