# Generated by Django 3.1.3 on 2020-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201112_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('', 'Choose Subject'), ('Advertising', 'Advertising'), ('Feature Request', 'Feature Request'), ('General Inquiry', 'General Inquiry'), ('Suggestion', 'Suggestion'), ('Support', 'Support')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='report_reason',
            field=models.CharField(choices=[('', 'Choose Subject'), ('Content', 'Inappropriate Content'), ('Images', 'Inappropriate Images'), ('Quality', 'Rude, Vulgar, or Offensive'), ('Ownership', 'Copyright / Trademark Issue'), ('Spam', 'Spam Content')], max_length=50),
        ),
    ]
