# Generated by Django 3.1.3 on 2021-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201115_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('spam', 'Spam')], default='unread', max_length=10),
        ),
    ]
