# Generated by Django 3.1.13 on 2021-12-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpost',
            name='post_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='status',
            field=models.CharField(choices=[('reported', 'Requires Review'), ('reviewing', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='reported', max_length=50, null=True),
        ),
    ]
