# Generated by Django 3.1.3 on 2021-01-27 08:03

import app.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='What is the name of this ad for your reference? This will not appear on the site.', max_length=200)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired'), ('paused', 'Paused'), ('review', 'In Review')], default='inactive', max_length=50)),
                ('type', models.CharField(choices=[('sidebar', 'Sidebar'), ('banner', 'Banner')], default='inactive', max_length=50, verbose_name='Type of Ad')),
                ('image', models.ImageField(blank=True, default=None, help_text='Upload an image for your ad in either jpg/png/gif format.', null=True, storage=app.storage_backends.S3AdsMediaStorage(), upload_to='')),
                ('contract_length', models.IntegerField(choices=[(7, 'One Week'), (14, 'Two Weeks'), (30, 'One Month'), (60, 'Two Months'), (90, 'Three Months')], default=7, help_text='Amount of times the ad will be active for.')),
                ('redirect_to', models.URLField(default=None, help_text='Enter the URL where the ad should be linked to. (Must include http:// or https://)', verbose_name='Send Ad To')),
                ('redirect_uuid', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_terms', models.BooleanField(default=False, verbose_name='Terms')),
                ('image_type', models.CharField(default=None, max_length=6)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ad',
                'verbose_name_plural': 'ads',
            },
        ),
    ]
