# Generated by Django 3.1.3 on 2021-01-19 13:40

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210118_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='read_terms',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to the Frum Philly advertising terms of service.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='contract_length',
            field=models.IntegerField(choices=[(7, 'One Week'), (14, 'Two Weeks'), (30, 'One Month'), (60, 'Two Months'), (90, 'Three Months')], default=7, help_text='Amount of times the ad will be active for.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Upload an image for your ad in either jpg/png/gif format. Dimensions should be 300x250.', null=True, storage=app.storage_backends.S3AdsMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='ad',
            name='redirect_to',
            field=models.URLField(default=None, help_text='Enter the URL where the ad should be linked to. (Must include http:// or https://)', verbose_name='Send Ad To'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(default='', help_text='What is the name of this ad for your reference? This will not appear on the site.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('banner', 'Banner')], default='inactive', max_length=50, verbose_name='Type of Ad'),
        ),
    ]
