# Generated by Django 3.1.3 on 2021-01-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20210128_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
