# Generated by Django 3.1.3 on 2021-01-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20210119_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='read_terms',
            field=models.BooleanField(default=False, verbose_name='Terms'),
        ),
    ]
