# Generated by Django 3.1.3 on 2021-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
