# Generated by Django 3.1.3 on 2021-01-21 12:06

import app.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20210120_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_type',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default=None, help_text='Upload an image for your ad in either jpg/png/gif format.', null=True, storage=app.storage_backends.S3AdsMediaStorage(), upload_to=''),
        ),
    ]
