# Generated by Django 3.1.3 on 2021-01-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_activated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='activated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
