# Generated by Django 3.1.3 on 2021-05-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20210128_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='contract_length',
            field=models.IntegerField(choices=[(30, 'One Month'), (60, 'Two Months'), (90, 'Three Months')], default=60, help_text='Amount of times the ad will be active for.'),
        ),
    ]
