# Generated by Django 3.1.12 on 2021-08-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210819_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumthread',
            old_name='description',
            new_name='content',
        ),
    ]
