# Generated by Django 3.1.12 on 2021-08-24 08:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210824_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=50000, unique=True),
        ),
    ]
