# Generated by Django 3.1.12 on 2021-09-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210826_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='content',
            field=models.TextField(max_length=50000, unique=True),
        ),
    ]
